name: CI Build

on:
  pull_request:
    branches:
      - main
      - v*.*

jobs:
  build:
    runs-on: self-hosted

    env:
      IS_CI: true
      Solution_Name: Core.sln
      VCPKG_DEFAULT_TRIPLET: x64-windows-static
      VCPKG_INSTALLED_DIR: vcpkg_installed

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0

      # Install the .NET Core workload
      - name: Install .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: |
            6.0.x
            7.0.x

      # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.0.2

      # Install latest CMake.
      - uses: lukka/get-cmake@latest

      # Restore from cache the previously built ports. If a "cache miss" occurs,
      # then vcpkg is bootstrapped. Since a the vcpkg.json is being used later on
      # to install the packages when `run-cmake` runs, no packages are installed at
      # this time.
      - name: Restore artifacts, and setup vcpkg
        uses: lukka/run-vcpkg@v10
        with:
          runVcpkgInstall: true
          doNotCache: true

      # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.0.2

      # Restore the application to populate the obj folder with RuntimeIdentifiers
      - name: Restore the application
        run: msbuild $env:Solution_Name /t:Restore /p:Configuration=Release

      # Build
      - name: Build
        run: |
          msbuild $env:Solution_Name -m -t:Build -p:Configuration=Release -p:Platform=x64

      # NuGet Push
      # - name: Push packages to github
      #   run: |
      #     dotnet nuget push publish\*.nupkg -k ${{ secrets.GITHUB_TOKEN }} -s https://nuget.pkg.github.com/il2cpptoolkit/index.json --skip-duplicate
